-- HỒI ÂM ĐAM MỸ V06
-- Migration bổ sung, không xóa truyện và không đặt lại số vote hiện có.
-- Nên sao lưu Supabase trước khi chạy toàn bộ file này trong SQL Editor.

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  title text not null,
  linkstory text,
  version text not null default 'Convert',
  note text not null default '',
  votes bigint not null default 0,
  status text not null default 'đề xuất',
  youtubelink text,
  createdat timestamptz not null default now()
);

alter table public.stories add column if not exists visible boolean not null default true;
alter table public.stories add column if not exists updatedat timestamptz not null default now();
alter table public.stories add column if not exists completedat timestamptz;
alter table public.stories add column if not exists deletedat timestamptz;
alter table public.stories add column if not exists thumbnail_url text;
alter table public.stories add column if not exists source_status text not null default 'normal';
alter table public.stories add column if not exists source_reason text not null default '';
alter table public.stories add column if not exists source_deadline timestamptz;
alter table public.stories add column if not exists source_warning_public boolean not null default false;
alter table public.stories add column if not exists views bigint not null default 0;
alter table public.stories add column if not exists youtube_clicks bigint not null default 0;

-- Database cũ chỉ cho phép "đề xuất" và "đang đọc".
-- Gỡ ràng buộc cũ trước khi chuẩn hóa, rồi tạo lại ngay bên dưới.
alter table public.stories drop constraint if exists stories_status_check;

update public.stories
set status = case
  when lower(trim(status)) in ('đang đọc', 'đang lên sóng') then 'đang lên sóng'
  when lower(trim(status)) = 'đã chọn' then 'đã chọn'
  when lower(trim(status)) = 'đã hoàn thành' then 'đã hoàn thành'
  else 'đề xuất'
end;

alter table public.stories
  add constraint stories_status_check
  check (status in ('đề xuất', 'đã chọn', 'đang lên sóng', 'đã hoàn thành'));

create index if not exists stories_visibility_status_idx
  on public.stories (visible, status, createdat desc);
create index if not exists stories_status_votes_idx
  on public.stories (status, votes desc);
create index if not exists stories_source_status_idx
  on public.stories (source_status, source_deadline);

create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  story_id bigint references public.stories(id) on delete set null,
  story_title text not null,
  donor_name text not null,
  amount_vnd bigint not null check (amount_vnd > 0),
  stone_count bigint not null default 0,
  suggested_votes integer not null default 0,
  applied_votes integer not null default 0,
  status text not null default 'pending',
  source_channel text not null default 'website',
  donor_email text,
  transaction_ref text,
  transfer_content text not null default '',
  donatedat timestamptz,
  note text not null default '',
  admin_note text not null default '',
  email_status text not null default 'not_requested',
  email_sentat timestamptz,
  email_error text not null default '',
  confirmedat timestamptz,
  appliedat timestamptz,
  createdat timestamptz not null default now(),
  updatedat timestamptz not null default now()
);

create unique index if not exists donations_transaction_ref_unique
  on public.donations (lower(transaction_ref))
  where transaction_ref is not null and length(trim(transaction_ref)) > 0;
create index if not exists donations_status_created_idx
  on public.donations (status, createdat desc);
create index if not exists donations_story_idx
  on public.donations (story_id, createdat desc);

create table if not exists public.source_replacements (
  id bigint generated by default as identity primary key,
  story_id bigint not null references public.stories(id) on delete cascade,
  replacement_url text not null,
  sender_name text,
  note text not null default '',
  status text not null default 'pending',
  admin_note text not null default '',
  createdat timestamptz not null default now(),
  reviewedat timestamptz
);

create index if not exists source_replacements_status_idx
  on public.source_replacements (status, createdat desc);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  tone text not null default 'info',
  display_mode text not null default 'banner',
  page_scope text not null default 'all',
  dismissible boolean not null default true,
  enabled boolean not null default true,
  startsat timestamptz,
  endsat timestamptz,
  createdat timestamptz not null default now(),
  updatedat timestamptz not null default now()
);

create table if not exists public.site_settings (
  id text primary key,
  settings jsonb not null default '{}'::jsonb,
  updatedat timestamptz not null default now()
);

insert into public.site_settings (id, settings)
values (
  'main',
  jsonb_build_object(
    'channelName', 'Hồi Âm Đam Mỹ',
    'tagline', 'Nơi cộng đồng cùng chọn câu chuyện tiếp theo.',
    'youtubeUrl', '',
    'logoUrl', '',
    'aboutTitle', 'Hồi Âm Đam Mỹ',
    'aboutBody', '',
    'contactEmail', '',
    'socialLinks', '[]'::jsonb,
    'donation', jsonb_build_object(
      'enabled', false,
      'bankName', '',
      'accountName', '',
      'accountNumber', '',
      'qrUrl', '',
      'transferTemplate', '{story} - {name}',
      'note', '',
      'unitLabel', 'Cá/Linh Thạch'
    )
  )
)
on conflict (id) do nothing;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  detail jsonb not null default '{}'::jsonb,
  createdat timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_idx
  on public.admin_audit_logs (createdat desc);

create or replace function public.increment_story_votes(
  story_id bigint,
  vote_delta integer default 1
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_votes bigint;
begin
  if vote_delta = 0 or vote_delta < -1000000 or vote_delta > 1000000 then
    raise exception 'vote_delta is out of range' using errcode = '22023';
  end if;

  update public.stories
  set votes = greatest(0, coalesce(votes, 0) + vote_delta),
      updatedat = now()
  where id = story_id
  returning votes into updated_votes;

  if updated_votes is null then
    raise exception 'story not found' using errcode = 'P0002';
  end if;

  return updated_votes;
end;
$$;

revoke all on function public.increment_story_votes(bigint, integer) from public;
revoke all on function public.increment_story_votes(bigint, integer) from anon;
revoke all on function public.increment_story_votes(bigint, integer) from authenticated;
grant execute on function public.increment_story_votes(bigint, integer) to service_role;

create or replace function public.apply_donation_votes(
  donation_id bigint,
  vote_count integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  donation_row public.donations%rowtype;
  total_votes bigint;
begin
  if vote_count < 0 or vote_count > 1000000 then
    raise exception 'vote_count is out of range' using errcode = '22023';
  end if;

  select * into donation_row
  from public.donations
  where id = donation_id
  for update;

  if donation_row.id is null then
    raise exception 'donation not found' using errcode = 'P0002';
  end if;

  if donation_row.status = 'applied' then
    select votes into total_votes from public.stories where id = donation_row.story_id;
    return jsonb_build_object(
      'already_applied', true,
      'applied_votes', donation_row.applied_votes,
      'total_votes', coalesce(total_votes, 0)
    );
  end if;

  if donation_row.status = 'rejected' then
    raise exception 'donation was rejected' using errcode = '22023';
  end if;

  if donation_row.story_id is null then
    raise exception 'donation has no story' using errcode = '22023';
  end if;

  update public.stories
  set votes = greatest(0, coalesce(votes, 0) + vote_count),
      updatedat = now()
  where id = donation_row.story_id
  returning votes into total_votes;

  if total_votes is null then
    raise exception 'story not found' using errcode = 'P0002';
  end if;

  update public.donations
  set status = 'applied',
      applied_votes = vote_count,
      appliedat = now(),
      updatedat = now(),
      email_status = case
        when donor_email is null or length(trim(donor_email)) = 0 then 'not_requested'
        else 'pending'
      end
  where id = donation_id;

  return jsonb_build_object(
    'already_applied', false,
    'applied_votes', vote_count,
    'total_votes', total_votes
  );
end;
$$;

revoke all on function public.apply_donation_votes(bigint, integer) from public;
revoke all on function public.apply_donation_votes(bigint, integer) from anon;
revoke all on function public.apply_donation_votes(bigint, integer) from authenticated;
grant execute on function public.apply_donation_votes(bigint, integer) to service_role;

create or replace function public.increment_story_metric(
  story_id bigint,
  metric_name text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  metric_value bigint;
begin
  if metric_name = 'view' then
    update public.stories
    set views = coalesce(views, 0) + 1
    where id = story_id
    returning views into metric_value;
  elsif metric_name = 'youtube' then
    update public.stories
    set youtube_clicks = coalesce(youtube_clicks, 0) + 1
    where id = story_id
    returning youtube_clicks into metric_value;
  else
    raise exception 'invalid metric' using errcode = '22023';
  end if;

  if metric_value is null then
    raise exception 'story not found' using errcode = 'P0002';
  end if;
  return metric_value;
end;
$$;

revoke all on function public.increment_story_metric(bigint, text) from public;
revoke all on function public.increment_story_metric(bigint, text) from anon;
revoke all on function public.increment_story_metric(bigint, text) from authenticated;
grant execute on function public.increment_story_metric(bigint, text) to service_role;

alter table public.donations enable row level security;
alter table public.source_replacements enable row level security;
alter table public.announcements enable row level security;
alter table public.site_settings enable row level security;
alter table public.admin_audit_logs enable row level security;

-- Các API V06 dùng service role ở máy chủ. Không đưa khóa này vào trình duyệt.
